/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.7.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the UpdateMemoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMemoryRequest{}

// UpdateMemoryRequest Request model for curating a single memory unit (edit / invalidate / revert).  Provide ``text`` to correct the fact, and/or ``state`` to invalidate ('invalidated') or revert ('valid') it. ``reason`` is optional free text recorded on the memory. At least one of ``text`` or ``state`` must be set. Only world/experience facts can be curated; observations are derived.
type UpdateMemoryRequest struct {
	Text NullableString `json:"text,omitempty"`
	State NullableString `json:"state,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
}

// NewUpdateMemoryRequest instantiates a new UpdateMemoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMemoryRequest() *UpdateMemoryRequest {
	this := UpdateMemoryRequest{}
	return &this
}

// NewUpdateMemoryRequestWithDefaults instantiates a new UpdateMemoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMemoryRequestWithDefaults() *UpdateMemoryRequest {
	this := UpdateMemoryRequest{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateMemoryRequest) GetText() string {
	if o == nil || IsNil(o.Text.Get()) {
		var ret string
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMemoryRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *UpdateMemoryRequest) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableString and assigns it to the Text field.
func (o *UpdateMemoryRequest) SetText(v string) {
	o.Text.Set(&v)
}
// SetTextNil sets the value for Text to be an explicit nil
func (o *UpdateMemoryRequest) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *UpdateMemoryRequest) UnsetText() {
	o.Text.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateMemoryRequest) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMemoryRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *UpdateMemoryRequest) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *UpdateMemoryRequest) SetState(v string) {
	o.State.Set(&v)
}
// SetStateNil sets the value for State to be an explicit nil
func (o *UpdateMemoryRequest) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *UpdateMemoryRequest) UnsetState() {
	o.State.Unset()
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateMemoryRequest) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMemoryRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *UpdateMemoryRequest) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *UpdateMemoryRequest) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *UpdateMemoryRequest) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *UpdateMemoryRequest) UnsetReason() {
	o.Reason.Unset()
}

func (o UpdateMemoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMemoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	return toSerialize, nil
}

type NullableUpdateMemoryRequest struct {
	value *UpdateMemoryRequest
	isSet bool
}

func (v NullableUpdateMemoryRequest) Get() *UpdateMemoryRequest {
	return v.value
}

func (v *NullableUpdateMemoryRequest) Set(val *UpdateMemoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMemoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMemoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMemoryRequest(val *UpdateMemoryRequest) *NullableUpdateMemoryRequest {
	return &NullableUpdateMemoryRequest{value: val, isSet: true}
}

func (v NullableUpdateMemoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMemoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


